/* El esquema que cree se llama RNPDNO */
Use RNPDNO;

/* Creacion de Tabla, ejecutar primero */
CREATE TABLE info01 (
consecutivo VARCHAR(7) DEFAULT NULL,
nro_reporte VARCHAR(1) DEFAULT NULL,
tipo_reporte VARCHAR(500) DEFAULT NULL,
datos_reporte_clb_status_victima VARCHAR(500) DEFAULT NULL,
datos_reporte_clb_feciniexpediente VARCHAR(100) DEFAULT NULL,
datos_reporte_clb_hipotesis VARCHAR(500) DEFAULT NULL,
datos_generales_clb_lugar_nacimiento VARCHAR(500) DEFAULT NULL,
datos_generales_clb_fecnacimiento VARCHAR(100) DEFAULT NULL,
datos_generales_clb_edad_a VARCHAR(100) DEFAULT NULL,
datos_generales_clb_edad_m VARCHAR(100) DEFAULT NULL,
datos_generales_clb_edad_d VARCHAR(100) DEFAULT NULL,
hechos_clb_fechorahechos VARCHAR(100) DEFAULT NULL,
hechos_clb_fechora_percato_desaparicion VARCHAR(100) DEFAULT NULL,
actividades_rutas_clb_fecha VARCHAR(100) DEFAULT NULL,
convida_rutas_clb_feclocalizacion VARCHAR(100) DEFAULT NULL,
convida_rutas_clb_lugarlocaliza VARCHAR(500) DEFAULT NULL,
sinvida_rutas_clb_feclocalizacion VARCHAR(100) DEFAULT NULL,
sinvida_rutas_clb_lugarlocaliza VARCHAR(500) DEFAULT NULL,
datos_reporte_clb_delito VARCHAR(500) DEFAULT NULL,
datos_reporte_clb_sexo VARCHAR(500) DEFAULT NULL,
datos_reporte_clb_genero VARCHAR(500) DEFAULT NULL,
datos_reporte_clb_nacionalidad VARCHAR(500) DEFAULT NULL,
datos_reporte_clb_estcivil VARCHAR(500) DEFAULT NULL,
lugarhechos_clb_estado VARCHAR(500) DEFAULT NULL,
lugarhechos_clb_municipio VARCHAR(500) DEFAULT NULL,
lugarhechos_clb_colonia VARCHAR(500) DEFAULT NULL,
lugarhechos_clb_estado2 VARCHAR(500) DEFAULT NULL,
lugarhechos_clb_municipio2 VARCHAR(500) DEFAULT NULL,
lugarhechos_clb_colonia2 VARCHAR(500) DEFAULT NULL,
hechos_clb_fechorahechos2 VARCHAR(100) DEFAULT NULL,
hechos_clb_fechora_percato_desaparicion2 VARCHAR(100) DEFAULT NULL,
datos_reporte_institucion VARCHAR(500) DEFAULT NULL,
datos_reporte_clb_status_victima2 VARCHAR(500) DEFAULT NULL,
datos_reporte_clb_feciniexpediente2 VARCHAR(100) DEFAULT NULL,
datos_reporte_clb_hipotesis2 VARCHAR(500) DEFAULT NULL,
datos_reporte_clb_delito2 VARCHAR(500) DEFAULT NULL,
datos_reporte_institucion2 VARCHAR(500) DEFAULT NULL 
);

/* Una vez que acabe el proceso en Python, correr desde aqui */

/* Limpieza de info */
UPDATE info01
SET datos_reporte_clb_genero = 'HOMBRE'
WHERE datos_reporte_clb_genero = 'MASCULINO';
UPDATE info01
SET datos_reporte_clb_genero = 'MUJER'
WHERE datos_reporte_clb_genero = 'FEMENINO';

UPDATE info01 SET tipo_reporte = NULL WHERE tipo_reporte LIKE '%SIN DATO%' OR tipo_reporte LIKE '%ELIMINADO%' OR tipo_reporte = '';
UPDATE info01 SET datos_reporte_clb_status_victima = NULL WHERE datos_reporte_clb_status_victima LIKE '%SIN DATO%' OR datos_reporte_clb_status_victima LIKE '%ELIMINADO%' OR datos_reporte_clb_status_victima = '';
UPDATE info01 SET datos_reporte_clb_feciniexpediente = NULL WHERE datos_reporte_clb_feciniexpediente LIKE '%SIN DATO%' OR datos_reporte_clb_feciniexpediente LIKE '%ELIMINADO%' OR datos_reporte_clb_feciniexpediente = '';
UPDATE info01 SET datos_reporte_clb_hipotesis = NULL WHERE datos_reporte_clb_hipotesis LIKE '%SIN DATO%' OR datos_reporte_clb_hipotesis LIKE '%ELIMINADO%' OR datos_reporte_clb_hipotesis = '';
UPDATE info01 SET datos_generales_clb_lugar_nacimiento = NULL WHERE datos_generales_clb_lugar_nacimiento LIKE '%SIN DATO%' OR datos_generales_clb_lugar_nacimiento LIKE '%ELIMINADO%' OR datos_generales_clb_lugar_nacimiento = '';
UPDATE info01 SET datos_generales_clb_fecnacimiento = NULL WHERE datos_generales_clb_fecnacimiento LIKE '%SIN DATO%' OR datos_generales_clb_fecnacimiento LIKE '%ELIMINADO%' OR datos_generales_clb_fecnacimiento = '';
UPDATE info01 SET datos_generales_clb_edad_a = NULL WHERE datos_generales_clb_edad_a LIKE '%SIN DATO%' OR datos_generales_clb_edad_a LIKE '%ELIMINADO%' OR datos_generales_clb_edad_a = '';
UPDATE info01 SET datos_generales_clb_edad_m = NULL WHERE datos_generales_clb_edad_m LIKE '%SIN DATO%' OR datos_generales_clb_edad_m LIKE '%ELIMINADO%' OR datos_generales_clb_edad_m = '';
UPDATE info01 SET datos_generales_clb_edad_d = NULL WHERE datos_generales_clb_edad_d LIKE '%SIN DATO%' OR datos_generales_clb_edad_d LIKE '%ELIMINADO%' OR datos_generales_clb_edad_d = '';
UPDATE info01 SET hechos_clb_fechorahechos = NULL WHERE hechos_clb_fechorahechos LIKE '%SIN DATO%' OR hechos_clb_fechorahechos LIKE '%ELIMINADO%' OR hechos_clb_fechorahechos = '';
UPDATE info01 SET hechos_clb_fechora_percato_desaparicion = NULL WHERE hechos_clb_fechora_percato_desaparicion LIKE '%SIN DATO%' OR hechos_clb_fechora_percato_desaparicion LIKE '%ELIMINADO%' OR hechos_clb_fechora_percato_desaparicion = '';
UPDATE info01 SET actividades_rutas_clb_fecha = NULL WHERE actividades_rutas_clb_fecha LIKE '%SIN DATO%' OR actividades_rutas_clb_fecha LIKE '%ELIMINADO%' OR actividades_rutas_clb_fecha = '';
UPDATE info01 SET convida_rutas_clb_feclocalizacion = NULL WHERE convida_rutas_clb_feclocalizacion LIKE '%SIN DATO%' OR convida_rutas_clb_feclocalizacion LIKE '%ELIMINADO%' OR convida_rutas_clb_feclocalizacion = '';
UPDATE info01 SET convida_rutas_clb_lugarlocaliza = NULL WHERE convida_rutas_clb_lugarlocaliza LIKE '%SIN DATO%' OR convida_rutas_clb_lugarlocaliza LIKE '%ELIMINADO%' OR convida_rutas_clb_lugarlocaliza = '';
UPDATE info01 SET sinvida_rutas_clb_feclocalizacion = NULL WHERE sinvida_rutas_clb_feclocalizacion LIKE '%SIN DATO%' OR sinvida_rutas_clb_feclocalizacion LIKE '%ELIMINADO%' OR sinvida_rutas_clb_feclocalizacion = '';
UPDATE info01 SET sinvida_rutas_clb_lugarlocaliza = NULL WHERE sinvida_rutas_clb_lugarlocaliza LIKE '%SIN DATO%' OR sinvida_rutas_clb_lugarlocaliza LIKE '%ELIMINADO%' OR sinvida_rutas_clb_lugarlocaliza = '';
UPDATE info01 SET datos_reporte_clb_delito = NULL WHERE datos_reporte_clb_delito LIKE '%SIN DATO%' OR datos_reporte_clb_delito LIKE '%ELIMINADO%' OR datos_reporte_clb_delito = '';
UPDATE info01 SET datos_reporte_clb_sexo = NULL WHERE datos_reporte_clb_sexo LIKE '%SIN DATO%' OR datos_reporte_clb_sexo LIKE '%ELIMINADO%' OR datos_reporte_clb_sexo = '';
UPDATE info01 SET datos_reporte_clb_genero = NULL WHERE datos_reporte_clb_genero LIKE '%SIN DATO%' OR datos_reporte_clb_genero LIKE '%ELIMINADO%' OR datos_reporte_clb_genero = '';
UPDATE info01 SET datos_reporte_clb_nacionalidad = NULL WHERE datos_reporte_clb_nacionalidad LIKE '%SIN DATO%' OR datos_reporte_clb_nacionalidad LIKE '%ELIMINADO%' OR datos_reporte_clb_nacionalidad = '';
UPDATE info01 SET datos_reporte_clb_estcivil = NULL WHERE datos_reporte_clb_estcivil LIKE '%SIN DATO%' OR datos_reporte_clb_estcivil LIKE '%ELIMINADO%' OR datos_reporte_clb_estcivil = '';
UPDATE info01 SET lugarhechos_clb_estado = NULL WHERE lugarhechos_clb_estado LIKE '%SIN DATO%' OR lugarhechos_clb_estado LIKE '%ELIMINADO%' OR lugarhechos_clb_estado = '';
UPDATE info01 SET lugarhechos_clb_municipio = NULL WHERE lugarhechos_clb_municipio LIKE '%SIN DATO%' OR lugarhechos_clb_municipio LIKE '%ELIMINADO%' OR lugarhechos_clb_municipio = '';
UPDATE info01 SET lugarhechos_clb_colonia = NULL WHERE lugarhechos_clb_colonia LIKE '%SIN DATO%' OR lugarhechos_clb_colonia LIKE '%ELIMINADO%' OR lugarhechos_clb_colonia = '';
UPDATE info01 SET lugarhechos_clb_estado2 = NULL WHERE lugarhechos_clb_estado2 LIKE '%SIN DATO%' OR lugarhechos_clb_estado2 LIKE '%ELIMINADO%' OR lugarhechos_clb_estado2 = '';
UPDATE info01 SET lugarhechos_clb_municipio2 = NULL WHERE lugarhechos_clb_municipio2 LIKE '%SIN DATO%' OR lugarhechos_clb_municipio2 LIKE '%ELIMINADO%' OR lugarhechos_clb_municipio2 = '';
UPDATE info01 SET lugarhechos_clb_colonia2 = NULL WHERE lugarhechos_clb_colonia2 LIKE '%SIN DATO%' OR lugarhechos_clb_colonia2 LIKE '%ELIMINADO%' OR lugarhechos_clb_colonia2 = '';
UPDATE info01 SET hechos_clb_fechorahechos2 = NULL WHERE hechos_clb_fechorahechos2 LIKE '%SIN DATO%' OR hechos_clb_fechorahechos2 LIKE '%ELIMINADO%' OR hechos_clb_fechorahechos2 = '';
UPDATE info01 SET hechos_clb_fechora_percato_desaparicion2 = NULL WHERE hechos_clb_fechora_percato_desaparicion2 LIKE '%SIN DATO%' OR hechos_clb_fechora_percato_desaparicion2 LIKE '%ELIMINADO%' OR hechos_clb_fechora_percato_desaparicion2 = '';
UPDATE info01 SET datos_reporte_institucion = NULL WHERE datos_reporte_institucion LIKE '%SIN DATO%' OR datos_reporte_institucion LIKE '%ELIMINADO%' OR datos_reporte_institucion = '';
UPDATE info01 SET datos_reporte_clb_status_victima2 = NULL WHERE datos_reporte_clb_status_victima2 LIKE '%SIN DATO%' OR datos_reporte_clb_status_victima2 LIKE '%ELIMINADO%' OR datos_reporte_clb_status_victima2 = '';
UPDATE info01 SET datos_reporte_clb_feciniexpediente2 = NULL WHERE datos_reporte_clb_feciniexpediente2 LIKE '%SIN DATO%' OR datos_reporte_clb_feciniexpediente2 LIKE '%ELIMINADO%' OR datos_reporte_clb_feciniexpediente2 = '';
UPDATE info01 SET datos_reporte_clb_hipotesis2 = NULL WHERE datos_reporte_clb_hipotesis2 LIKE '%SIN DATO%' OR datos_reporte_clb_hipotesis2 LIKE '%ELIMINADO%' OR datos_reporte_clb_hipotesis2 = '';
UPDATE info01 SET datos_reporte_clb_delito2 = NULL WHERE datos_reporte_clb_delito2 LIKE '%SIN DATO%' OR datos_reporte_clb_delito2 LIKE '%ELIMINADO%' OR datos_reporte_clb_delito2 = '';
UPDATE info01 SET datos_reporte_institucion2 = NULL WHERE datos_reporte_institucion2 LIKE '%SIN DATO%' OR datos_reporte_institucion2 LIKE '%ELIMINADO%' OR datos_reporte_institucion2 = '';

TRUNCATE TABLE INFO_V2;
DROP TABLE INFO_V2;

CREATE TABLE INFO_V2
SELECT 
CAST(CONSECUTIVO AS SIGNED) AS CONSECUTIVO,
CAST(NRO_REPORTE AS SIGNED) AS NRO_REPORTE,
TIPO_REPORTE,
CASE WHEN (TRIM(DATOS_REPORTE_INSTITUCION) = 'SE DESCONOCE' OR TRIM(DATOS_REPORTE_INSTITUCION) = 'PORTAL') AND DATOS_REPORTE_INSTITUCION2 IS NOT NULL THEN TRIM(DATOS_REPORTE_INSTITUCION2) ELSE TRIM(DATOS_REPORTE_INSTITUCION) END AS DATOS_REPORTE_INSTITUCION,
CASE WHEN TRIM(DATOS_REPORTE_CLB_STATUS_VICTIMA2) LIKE 'LOCALIZADA%' THEN TRIM(DATOS_REPORTE_CLB_STATUS_VICTIMA2) ELSE TRIM(DATOS_REPORTE_CLB_STATUS_VICTIMA) END AS DATOS_REPORTE_STATUS_VICTIMA,
STR_TO_DATE(IFNULL(datos_reporte_clb_feciniexpediente,datos_reporte_clb_feciniexpediente2),'%d/%m/%Y') AS DATOS_REPORTE_FECINIEXPEDIENTE,
CASE WHEN (TRIM(datos_reporte_clb_hipotesis) = 'SE DESCONOCE' OR datos_reporte_clb_hipotesis IS NULL) AND datos_reporte_clb_hipotesis2 IS NOT NULL THEN TRIM(datos_reporte_clb_hipotesis2) ELSE TRIM(datos_reporte_clb_hipotesis) END AS DATOS_REPORTE_HIPOTESIS,
CASE WHEN datos_reporte_clb_delito IS NULL AND datos_reporte_clb_delito2 IS NOT NULL THEN TRIM(datos_reporte_clb_delito2) ELSE TRIM(datos_reporte_clb_delito) END AS DATOS_REPORTE_DELITO,
CASE WHEN (TRIM(datos_reporte_clb_sexo) = 'INDETERMINADO' OR datos_reporte_clb_sexo IS NULL) AND datos_reporte_clb_genero IS NOT NULL THEN TRIM(datos_reporte_clb_genero) ELSE TRIM(datos_reporte_clb_sexo) END AS DATOS_REPORTE_SEXO, 
TRIM(datos_reporte_clb_nacionalidad) AS DATOS_REPORTE_NACIONALIDAD,
TRIM(datos_reporte_clb_estcivil) AS DATOS_REPORTE_ESTCIVIL,
TRIM(datos_generales_clb_lugar_nacimiento) AS DATOS_GENERALES_LUGAR_NACIMIENTO,
STR_TO_DATE(datos_generales_clb_fecnacimiento,'%d/%m/%Y') AS DATOS_GENERALES_FECHA_NACIMIENTO,
CAST(datos_generales_clb_edad_a AS SIGNED) AS DATOS_GENERALES_EDAD_AÑOS,
CAST(datos_generales_clb_edad_m AS SIGNED) AS DATOS_GENERALES_EDAD_MESES,
CAST(datos_generales_clb_edad_d AS SIGNED) AS DATOS_GENERALES_EDAD_DIAS,
STR_TO_DATE(LEFT(IFNULL(IFNULL(hechos_clb_fechorahechos,hechos_clb_fechorahechos2),IFNULL(hechos_clb_fechora_percato_desaparicion,hechos_clb_fechora_percato_desaparicion2)),10),'%d/%m/%Y') AS HECHOS_FECHA_HECHOS,
STR_TO_DATE(LEFT(IFNULL(IFNULL(IFNULL(hechos_clb_fechorahechos,hechos_clb_fechorahechos2),IFNULL(hechos_clb_fechora_percato_desaparicion,hechos_clb_fechora_percato_desaparicion2)),IFNULL(datos_reporte_clb_feciniexpediente,datos_reporte_clb_feciniexpediente2)),10),'%d/%m/%Y') AS FECHA_COMODIN,
STR_TO_DATE(LEFT(IFNULL(hechos_clb_fechora_percato_desaparicion,hechos_clb_fechora_percato_desaparicion2),10),'%d/%m/%Y') AS HECHOS_FECHA_PERCATA_DESAPARICION,
CASE WHEN (TRIM(lugarhechos_clb_estado) = 'SE DESCONOCE' OR lugarhechos_clb_estado IS NULL) AND lugarhechos_clb_estado2 IS NOT NULL THEN TRIM(lugarhechos_clb_estado2) ELSE TRIM(lugarhechos_clb_estado) END AS HECHOS_ESTADO, 
CASE WHEN (TRIM(lugarhechos_clb_municipio) = 'SE DESCONOCE' OR lugarhechos_clb_municipio IS NULL) AND lugarhechos_clb_municipio2 IS NOT NULL THEN TRIM(lugarhechos_clb_municipio2) ELSE TRIM(lugarhechos_clb_municipio) END AS HECHOS_MUNICIPIO, 
CASE WHEN (TRIM(lugarhechos_clb_colonia) = 'SE DESCONOCE' OR lugarhechos_clb_colonia IS NULL) AND lugarhechos_clb_colonia2 IS NOT NULL THEN TRIM(lugarhechos_clb_colonia2) ELSE TRIM(lugarhechos_clb_colonia) END AS HECHOS_COLONIA
FROM info01;

UPDATE INFO_V2 
SET DATOS_REPORTE_FECINIEXPEDIENTE = NULL 
WHERE YEAR(DATOS_REPORTE_FECINIEXPEDIENTE) < 1900;
UPDATE INFO_V2 
SET DATOS_GENERALES_FECHA_NACIMIENTO = NULL 
WHERE YEAR(DATOS_GENERALES_FECHA_NACIMIENTO) < 1800;


TRUNCATE TABLE INFO_V3;
DROP TABLE INFO_V3;

CREATE TABLE INFO_V3
SELECT 
CONSECUTIVO,
NRO_REPORTE,
TIPO_REPORTE,
DATOS_REPORTE_INSTITUCION,
SUBSTRING_INDEX(DATOS_REPORTE_INSTITUCION, "ESTADO DE ",-1) AS ESTADO1, 
LOCATE("ESTADO DE ",DATOS_REPORTE_INSTITUCION) AS ESTADO_ENCONTRADO_1,
SUBSTRING_INDEX(DATOS_REPORTE_INSTITUCION, "DE ",-1) AS ESTADO2, 
LOCATE("DE ",DATOS_REPORTE_INSTITUCION) AS ESTADO_ENCONTRADO_2,
DATOS_REPORTE_STATUS_VICTIMA,
DATOS_REPORTE_FECINIEXPEDIENTE,
DATOS_REPORTE_HIPOTESIS,
DATOS_REPORTE_DELITO,
DATOS_REPORTE_SEXO,
DATOS_REPORTE_NACIONALIDAD,
DATOS_REPORTE_ESTCIVIL,
DATOS_GENERALES_LUGAR_NACIMIENTO,
DATOS_GENERALES_FECHA_NACIMIENTO,
DATOS_GENERALES_EDAD_AÑOS AS DATOS_GENERALES_EDAD,
FLOOR(CASE WHEN FECHA_COMODIN IS NOT NULL AND DATOS_GENERALES_FECHA_NACIMIENTO IS NOT NULL AND YEAR(FECHA_COMODIN) > YEAR(DATOS_GENERALES_FECHA_NACIMIENTO) THEN YEAR(FECHA_COMODIN) - YEAR(DATOS_GENERALES_FECHA_NACIMIENTO) + ((MONTH(FECHA_COMODIN)-MONTH(DATOS_GENERALES_FECHA_NACIMIENTO))/12) ELSE NULL END) AS EDAD_ALTERNA, 
DATE_ADD(DATE_ADD(DATE_ADD(DATOS_GENERALES_FECHA_NACIMIENTO, INTERVAL IFNULL(DATOS_GENERALES_EDAD_AÑOS,0) YEAR), INTERVAL IFNULL(DATOS_GENERALES_EDAD_MESES,0) MONTH), INTERVAL IFNULL(DATOS_GENERALES_EDAD_DIAS,0) DAY) AS FECHA_COMODIN_HECHOS,
HECHOS_FECHA_HECHOS,
HECHOS_FECHA_PERCATA_DESAPARICION,
HECHOS_ESTADO,
HECHOS_MUNICIPIO,
HECHOS_COLONIA
FROM INFO_V2;

UPDATE INFO_V3
SET DATOS_GENERALES_EDAD = EDAD_ALTERNA 
WHERE DATOS_GENERALES_EDAD IS NULL AND EDAD_ALTERNA IS NOT NULL;

UPDATE INFO_V3
SET DATOS_GENERALES_EDAD = EDAD_ALTERNA 
WHERE ABS(DATOS_GENERALES_EDAD - EDAD_ALTERNA) > 0 AND DATOS_GENERALES_FECHA_NACIMIENTO > '1900-01-01';

UPDATE INFO_V3
SET DATOS_GENERALES_EDAD = NULL 
WHERE DATOS_GENERALES_FECHA_NACIMIENTO <= '1900-01-01' AND DATOS_GENERALES_EDAD > 100;

UPDATE INFO_V3
SET HECHOS_FECHA_HECHOS = FECHA_COMODIN_HECHOS 
WHERE HECHOS_FECHA_HECHOS IS NULL AND FECHA_COMODIN_HECHOS IS NOT NULL AND DATOS_GENERALES_EDAD IS NOT NULL;

UPDATE INFO_V3
SET HECHOS_FECHA_HECHOS = NULL 
WHERE HECHOS_FECHA_HECHOS < '1960-01-01' OR HECHOS_FECHA_HECHOS > '2024-05-31';

UPDATE INFO_V3
SET HECHOS_FECHA_HECHOS = DATOS_REPORTE_FECINIEXPEDIENTE
WHERE HECHOS_FECHA_HECHOS IS NULL AND DATOS_REPORTE_FECINIEXPEDIENTE IS NOT NULL;

UPDATE INFO_V3
SET HECHOS_FECHA_HECHOS = NULL 
WHERE HECHOS_FECHA_HECHOS < '1960-01-01' OR HECHOS_FECHA_HECHOS > '2024-05-31';


TRUNCATE TABLE INFO_V4;
DROP TABLE INFO_V4;

CREATE TABLE INFO_V4
SELECT 
CONSECUTIVO,
NRO_REPORTE,
TIPO_REPORTE,
CASE WHEN SUBSTRING_INDEX(DATOS_REPORTE_INSTITUCION,' ',2) LIKE 'COMISION %' THEN SUBSTRING_INDEX(DATOS_REPORTE_INSTITUCION,' ',4) 
WHEN SUBSTRING_INDEX(DATOS_REPORTE_INSTITUCION,' ',2) LIKE 'FISCALIA%' AND SUBSTRING_INDEX(DATOS_REPORTE_INSTITUCION,' ',2) LIKE '%ESPECIAL%' THEN 'FISCALIA ESPECIAL' 
WHEN SUBSTRING_INDEX(DATOS_REPORTE_INSTITUCION,' ',2) LIKE 'FISCALIA%' AND DATOS_REPORTE_INSTITUCION LIKE '%LA REPUBLICA' THEN DATOS_REPORTE_INSTITUCION
WHEN SUBSTRING_INDEX(DATOS_REPORTE_INSTITUCION,' ',2) LIKE 'FISCALIA%' THEN 'FISCALIA GENERAL DEL ESTADO'
WHEN SUBSTRING_INDEX(DATOS_REPORTE_INSTITUCION,' ',2) LIKE 'PROCURADURIA %' THEN 'PROCURADURIA GENERAL DE JUSTICIA DEL ESTADO'
WHEN SUBSTRING_INDEX(DATOS_REPORTE_INSTITUCION,' ',2) LIKE 'SUBPROCURADURIA %' THEN 'SUBPROCURADURIA'
ELSE SUBSTRING_INDEX(DATOS_REPORTE_INSTITUCION,' ',2) END AS DATOS_REPORTE_INSTITUCION_TIPO,
CASE 
WHEN DATOS_REPORTE_INSTITUCION IN 
('COMISION NACIONAL DE BUSQUEDA DE PERSONAS',
'SUBPROCURADURIA DE DERECHOS HUMANOS, PREVENCION DEL DELITO Y SERVICIOS A LA COMUNIDAD',
'FISCALIA ESPECIAL PARA LOS DELITOS DE VIOLENCIA CONTRA LAS MUJERES Y TRATA DE PERSONAS',
'SUBPROCURADURIA ESPECIALIZADA EN INVESTIGACION DE DELINCUENCIA ORGANIZADA',
'SUBPROCURADURIA ESPECIALIZADA EN INVESTIGACION DE DELITOS FEDERALES',
'SUBPROCURADURIA DE CONTROL REGIONAL, PROCEDIMIENTOS PENALES Y AMPARO',
'FISCALIA GENERAL DE LA REPUBLICA')
THEN NULL
WHEN ESTADO_ENCONTRADO_1 > 0 THEN ESTADO1 
WHEN ESTADO_ENCONTRADO_1 = 0 AND ESTADO_ENCONTRADO_2 > 0 THEN ESTADO2
WHEN ESTADO_ENCONTRADO_2 = 0 AND DATOS_REPORTE_INSTITUCION = 'FISCALIA GENERAL DEL ESTADO BAJA CALIFORNIA' THEN 'BAJA CALIFORNIA'
ELSE NULL 
END AS DATOS_REPORTE_INSTITUCION_ESTADO,
DATOS_REPORTE_STATUS_VICTIMA,
DATOS_REPORTE_HIPOTESIS,
DATOS_REPORTE_DELITO,
DATOS_REPORTE_SEXO,
DATOS_REPORTE_NACIONALIDAD,
DATOS_REPORTE_ESTCIVIL,
DATOS_GENERALES_LUGAR_NACIMIENTO,
DATOS_GENERALES_EDAD,
DATOS_GENERALES_FECHA_NACIMIENTO,
HECHOS_FECHA_HECHOS,
HECHOS_ESTADO,
HECHOS_MUNICIPIO,
HECHOS_COLONIA 
FROM INFO_V3;


UPDATE INFO_V4 
SET HECHOS_ESTADO = DATOS_REPORTE_INSTITUCION_ESTADO
WHERE HECHOS_ESTADO IS NULL AND DATOS_REPORTE_INSTITUCION_ESTADO IS NOT NULL 
AND DATOS_REPORTE_INSTITUCION_ESTADO NOT IN ('SE DESCONOCE');

UPDATE INFO_V4 
SET HECHOS_ESTADO = 'MEXICO'
WHERE HECHOS_ESTADO = 'ESTADO DE MEXICO';

UPDATE INFO_V4 
SET DATOS_GENERALES_LUGAR_NACIMIENTO = 'MEXICO'
WHERE DATOS_GENERALES_LUGAR_NACIMIENTO  = 'ESTADO DE MEXICO';

TRUNCATE TABLE INFO_V5;
DROP TABLE INFO_V5; 

CREATE TABLE INFO_V5
SELECT A.*,
B.ID AS ID_HECHOS_ESTADO,
B.NOMBRE AS NOMBRE_HECHOS_ESTADO,
C.ID AS ID_LUGAR_NACIMIENTO,
C.NOMBRE AS NOMBRE_LUGAR_NACIMIENTO
FROM INFO_V4 A 
LEFT JOIN estados B
ON(A.HECHOS_ESTADO = TRIM(B.NOMBRE)
OR A.HECHOS_ESTADO = SUBSTRING_INDEX(TRIM(B.NOMBRE),' ',1))
LEFT JOIN estados C 
ON(A.DATOS_GENERALES_LUGAR_NACIMIENTO = TRIM(C.NOMBRE)
OR A.DATOS_GENERALES_LUGAR_NACIMIENTO = SUBSTRING_INDEX(TRIM(C.NOMBRE),' ',1));

TRUNCATE TABLE INFO_V6;
DROP TABLE INFO_V6; 

CREATE TABLE INFO_V6
SELECT A.*,
B.ID AS ID_HECHOS_MUNICIPIO,
B.NOMBRE AS NOMBRE_HECHOS_MUNICIPIO 
FROM INFO_V5 A 
LEFT JOIN municipios B
ON(A.ID_HECHOS_ESTADO = B.ESTADO_ID
AND A.HECHOS_MUNICIPIO = TRIM(B.NOMBRE));

UPDATE INFO_V6 
SET 
HECHOS_ESTADO = 'COAHUILA',
ID_HECHOS_ESTADO = 5,
NOMBRE_HECHOS_ESTADO = 'Coahuila de Zaragoza',
ID_HECHOS_MUNICIPIO = 37,
NOMBRE_HECHOS_MUNICIPIO = 'Allende' 
WHERE HECHOS_MUNICIPIO = 'ALLENDE' 
AND ID_HECHOS_ESTADO = 9;

UPDATE INFO_V6 
SET 
HECHOS_ESTADO = 'MEXICO',
ID_HECHOS_ESTADO = 15,
NOMBRE_HECHOS_ESTADO = 'México',
ID_HECHOS_MUNICIPIO = 745,
NOMBRE_HECHOS_MUNICIPIO = 'Tecámac' 
WHERE HECHOS_MUNICIPIO = 'TECÁMAC' 
AND ID_HECHOS_ESTADO = 5;

UPDATE INFO_V6 
SET 
HECHOS_ESTADO = 'PUEBLA',
ID_HECHOS_ESTADO = 21,
NOMBRE_HECHOS_ESTADO = 'Puebla',
ID_HECHOS_MUNICIPIO = 1632,
NOMBRE_HECHOS_MUNICIPIO = 'Chignahuapan' 
WHERE HECHOS_MUNICIPIO = 'CHIGNAHUAPAN' 
AND ID_HECHOS_ESTADO = 16;

UPDATE INFO_V6 
SET 
HECHOS_ESTADO = 'MEXICO',
ID_HECHOS_ESTADO = 15,
NOMBRE_HECHOS_ESTADO = 'México',
ID_HECHOS_MUNICIPIO = 722,
NOMBRE_HECHOS_MUNICIPIO = 'Nezahualcóyotl' 
WHERE HECHOS_MUNICIPIO = 'NEZAHUALCÓYOTL' 
AND ID_HECHOS_ESTADO = 16;

UPDATE INFO_V6 
SET 
HECHOS_ESTADO = 'MEXICO',
ID_HECHOS_ESTADO = 15,
NOMBRE_HECHOS_ESTADO = 'México',
ID_HECHOS_MUNICIPIO = 697,
NOMBRE_HECHOS_MUNICIPIO = 'Ecatepec de Morelos' 
WHERE HECHOS_MUNICIPIO = 'ECATEPEC DE MORELOS' 
AND ID_HECHOS_ESTADO = 25;

UPDATE INFO_V6 
SET 
HECHOS_ESTADO = 'CIUDAD DE MEXICO',
ID_HECHOS_ESTADO = 9,
NOMBRE_HECHOS_ESTADO = 'Ciudad de México',
ID_HECHOS_MUNICIPIO = 282,
NOMBRE_HECHOS_MUNICIPIO = 'Álvaro Obregón' 
WHERE HECHOS_MUNICIPIO = 'ÁLVARO OBREGÓN' 
AND ID_HECHOS_ESTADO = 25;

UPDATE INFO_V6 
SET DATOS_REPORTE_STATUS_VICTIMA = 'NO LOCALIZADA'
WHERE DATOS_REPORTE_STATUS_VICTIMA IN ('DESAPARECIDA','DESAPARECIDA/NO LOCALIZADA');

TRUNCATE TABLE INFO_VF;
DROP TABLE INFO_VF; 

CREATE TABLE INFO_VF
SELECT 
CONSECUTIVO,
NRO_REPORTE,
TIPO_REPORTE,
DATOS_REPORTE_INSTITUCION_TIPO AS INSTITUCION_TIPO,
DATOS_REPORTE_INSTITUCION_ESTADO AS INSTITUCION_ESTADO,
DATOS_REPORTE_STATUS_VICTIMA AS STATUS_VICTIMA,
DATOS_REPORTE_HIPOTESIS AS HIPOTESIS,
DATOS_REPORTE_DELITO AS DELITO,
DATOS_REPORTE_SEXO AS SEXO,
DATOS_REPORTE_ESTCIVIL AS EST_CIVIL,
DATOS_REPORTE_NACIONALIDAD AS NACIONALIDAD,
DATOS_GENERALES_LUGAR_NACIMIENTO AS LUGAR_NACIMIENTO,
ID_LUGAR_NACIMIENTO AS LUGAR_NACIMIENTO_ID,
NOMBRE_LUGAR_NACIMIENTO AS LUGAR_NACIMIENTO_NOMBRE,
DATOS_GENERALES_EDAD AS EDAD,
DATOS_GENERALES_FECHA_NACIMIENTO AS FECHA_NACIMIENTO,
HECHOS_FECHA_HECHOS AS HECHOS_FECHA,
HECHOS_ESTADO,
ID_HECHOS_ESTADO AS HECHOS_ESTADO_ID,
NOMBRE_HECHOS_ESTADO AS HECHOS_ESTADO_NOMBRE,
HECHOS_MUNICIPIO,
ID_HECHOS_MUNICIPIO AS HECHOS_MUNICIPIO_ID,
NOMBRE_HECHOS_MUNICIPIO AS HECHOS_MUNICIPIO_NOMBRE,
CONCAT(B.CLAVE,IFNULL(C.CLAVE,'')) AS HECHOS_CLAVE_GEO,
IFNULL(D.ALTITUD,E.ALTITUD) AS ALTITUD,
IFNULL(D.POBLACION,E.POBLACION) AS POBLACION,
IFNULL(D.POBLACION_H,E.POBLACION_H) AS POBLACION_H,
IFNULL(D.POBLACION_M,E.POBLACION_M) AS POBLACION_M,
IFNULL(D.VIVIENDAS,E.VIVIENDAS) AS VIVIENDAS
FROM INFO_V6 A LEFT JOIN estados B
ON(A.ID_HECHOS_ESTADO = B.ID)
LEFT JOIN municipios C
ON(A.ID_HECHOS_ESTADO = C.ESTADO_ID
AND A.ID_HECHOS_MUNICIPIO = C.ID) 
LEFT JOIN 
(
	SELECT MUNICIPIO_ID, 
	ROUND(AVG(ALTITUD),0) AS ALTITUD, 
	SUM(POBLACION) AS POBLACION, 
	ROUND((SUM(MASCULINO)/(SUM(MASCULINO)+SUM(FEMENINO)))*SUM(POBLACION),0) AS POBLACION_H, 
	ROUND((SUM(FEMENINO)/(SUM(MASCULINO)+SUM(FEMENINO)))*SUM(POBLACION),0) AS POBLACION_M, 
	SUM(VIVIENDAS) AS VIVIENDAS
	FROM localidades 
	WHERE activo = 1
	GROUP BY MUNICIPIO_ID
) D
ON(A.ID_HECHOS_MUNICIPIO = D.MUNICIPIO_ID)
LEFT JOIN 
(
	SELECT Y.ESTADO_ID, 
	ROUND(AVG(ALTITUD),0) AS ALTITUD, 
	SUM(POBLACION) AS POBLACION, 
	ROUND((SUM(MASCULINO)/(SUM(MASCULINO)+SUM(FEMENINO)))*SUM(POBLACION),0) AS POBLACION_H, 
	ROUND((SUM(FEMENINO)/(SUM(MASCULINO)+SUM(FEMENINO)))*SUM(POBLACION),0) AS POBLACION_M, 
	SUM(VIVIENDAS) AS VIVIENDAS
	FROM localidades X LEFT JOIN municipios Y 
	ON(X.municipio_id = Y.ID)
	WHERE X.activo = 1
	GROUP BY Y.ESTADO_ID
) E 
ON(A.ID_HECHOS_ESTADO = E.ESTADO_ID);

TRUNCATE TABLE INFO_V2;
DROP TABLE INFO_V2;
TRUNCATE TABLE INFO_V3;
DROP TABLE INFO_V3;
TRUNCATE TABLE INFO_V4;
DROP TABLE INFO_V4;
TRUNCATE TABLE INFO_V5;
DROP TABLE INFO_V5;

SHOW COLUMNS FROM INFO_VF;
